### ISSUE TITLE
What is 'q' in inputs?

### ISSUE THREAD

**Issue by MartinThoma** [TensorVision/TensorVision#27]
I would like to add this to the README.md.

What is `q` in `inputs(hypes, q, phase, data_dir)`?

**Comment by MarvinTeichmann** [comment]
The output of `create_queues`. It is meant to be a queues or a dictionary of queues yielding the input in a separate thread. Queues are created by `create_queues` and passed to `start_enqueuing_threads` once and `inputs` each time an input shell be produced. All of those three functions are part of `data_input`. `q` is not used in the main script or passed to some other modules. The User has therefore the freedom to utilize `q` however he wants.

If the user does not want to use queues, he might return `None`.

**Comment by MarvinTeichmann** [comment]
Queues are utilized in the MediSeg ([input.py](https://github.com/TensorVision/MediSeg/blob/master/model/medseg_input.py)). Have a look at it, if you want to see how one can utilize this.
