### ISSUE TITLE
Not useable in this Version

### ISSUE THREAD

**Issue by MarvinTeichmann** [TensorVision/TensorVision#4]
The Toolkit is not useable in this Version.

1) Importing 'train.py' through error 'ImportError: No module named config'
2) There is no command line interface.

I am a bit tired right now, planning to look at this tomorrow.  Should we provide a python interface?

**Comment by MartinThoma** [comment]
> Should we provide a python interface?

It depends on what we want to do. Currently, I think we only say the user what he has to implement. Then he uses a CLI.

**Comment by MarvinTeichmann** [comment]
I fixed Bug 1) in fe9417641232aa676ed234a3e6ce51fa49667552 and 2) in 954714373197579a48823e95596ec9dfffc9413e .

Commit 954714373197579a48823e95596ec9dfffc9413e provides a CLI by copying train.py to bin/tv-train. This Solution works with the current Flag infrastructure. I am however open to discuss different Solutions.

**Comment by MartinThoma** [comment]
Mavin, you should make a feature branch for changes and discuss them before you merge them in the master branch. But let's continue the discussion in #5

**Comment by MarvinTeichmann** [comment]
In this case I disagree. The TV Version was not usable before fe9417641232aa676ed234a3e6ce51fa49667552. I found fixing this was kind of urgent. For future changes I will use a feature branch.

From know we should try to keep the master branch functional.
