### ISSUE TITLE
Which flag parser to use?

### ISSUE THREAD

**Issue by MarvinTeichmann** [TensorVision/TensorVision#5]
Currently we are using `tf.app.flags` to provide command line flags. In general `argparse.ArgumentParser()` seems to be a popular choice. Should we switch?

pro: 
- argparse.ArgumentParser() is widely used and the user might be familiar
- argparse.ArgumentParser allows to create subparser, this is a good feature if we want to provide an CLI. (I do not know how to build do that with tensorflow)

contra:
- User might want to use `tf.app.flags`. And using `tf.app.flags` is incompatible with argparse.ArgumentParser
- switching comes with an afford.

**Comment by MartinThoma** [comment]
I am not sure what `tf.app` is. Where did you find it? Is there any documentation?

Anyway, I've just added a CLI (see https://github.com/TensorVision/TensorVision/tree/CLI). For the development setup, don't forget to set the softlink, e.g. `~/bin/$ ln -s ~/GitHub/TensorVision/bin/tv .`

**Comment by MarvinTeichmann** [comment]
`tf.app.flag` is the flag interface in Tensorflow. It is implemented in `tensorflow/tensorflow/python/platform/flags.py`. We are using `tf.app.flag` right now to define Flags (e.g. `--config`, to specify the model and `--name` to give the logdir a name). 

Unfortunately `tf.app.flag` seem to be not compatible with the solution you provided. Running 
`tv train --config mediseg.json' will result in an error.

**Comment by MartinThoma** [comment]
I would prefer to have a single command `tv` which makes use of subcommands like `tv train` and `tv test` instead of multiple high-level commands like `tv-train` and `tv-test`. The advantage is simple:

`tv --help` will list all subcommands, whereas the user has to know that both, `tv-train` and `tv-test` exist.

Adding more flags with `argparse` is easy. I don't see an advantage in using the `tensorflow/tensorflow/python/platform/flags.py`

**Comment by MarvinTeichmann** [comment]
Regarding flags, right now I tend to prefer to stick to  `tf.app.flags`. I see two advantages of `tf.app.flags`:
1) `tf.app.flags` are very flexible. They can be defined anywhere in the Tensorflow Code and will be accessible from outside. at any position in the script. Which is very good for our purpose. 
If a user for example wants to control their input via flag (e.g. data_augmentation options) they can define a Flagn option inside their input_file. This option will automatically propagate through, the user does not need to modify `train.py` to make it available.  (As far as I know, argparse does not provide this kind of flexibility. Am I right with that?)
2) `tf.app.flags` is Tensorflow standard. So users might widely use that. Right now it is very easy to port any model to Tensorvision and I find that very crucial. If we are not supporting Tensorflow flags Models which use them need to be adjusted.

**Comment by MarvinTeichmann** [comment]
In my [config.py](https://github.com/MarvinTeichmann/KittiSeg/blob/master/config.py) you can find a further example where the flexibility of Tensorflow Flags are very handy. Basically I need a way to define on which GPU tensorflow runs for each run.

I believe this is a pretty standard usecase. We have a bunch of multi-gpu servers here (8-16 GPUs), where I can (soft) reserve one of them. (E.g. GPU 3). I am responsible to make sure, that TF only uses the GPU I am assigned to in this run. One could easily code such a feature hard into the Toolkit. However I like that it is possible to handle that in the config, as the GPU/Server situation might widely differ between users.

**Comment by MartinThoma** [comment]
> 1) `tf.app.flags` are very flexible. They can be defined anywhere in the Tensorflow Code and will be accessible from outside. at any position in the script. [...] As far as I know, argparse does not provide this kind of flexibility. Am I right with that?

I didn't try it by now, but I am pretty sure you can get the same when you assign the arguments to a module which does not get reloaded (e.g. `import tensorflow as tf` in the script which takes care of command line parsing and just make `tf.whatever_here_its_global = get_parser().parse_args()`). So like this (or similar) the user should get all parsed arguments. However, you want to give the user also the possibility to add new arguments. So you need to give the user the parser object (see [example](https://martin-thoma.com/how-to-parse-command-line-arguments-in-python/#tocAnchor-1-1-5)).

> 2) `tf.app.flags` is Tensorflow standard. 

Can you give me 3 examples where it is used? Probably there is a common way to combine argparse and tf flags?

**Comment by MartinThoma** [comment]
Ok, forget it. They use argparse anyway. I'm happy with it :-)

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/default/_flags.py#L21

So lets use the TensorFlow parser.

**Comment by MartinThoma** [comment]
But I still think we should use subcommands (`tv train`) instead of many commands (`tv-train`) due to the fact that the user only has to know one command then.

edit: Lets see if somebody knows the answer - http://stackoverflow.com/q/36803452/562769

**Comment by MarvinTeichmann** [comment]
I agree with using separate commands. Additionally I would like the interface to be:
`tv train <model.json>`. Right now it is `tv train --config=<model.json>`.

**Comment by MarvinTeichmann** [comment]
> Can you give me 3 examples where it is used? Probably there is a common way to combine argparse and tf flags?

I was referring to the wide usage of tf.flags inside tensorflow (e.g. tutorials and example models). See for example:  
[https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/models/rnn/translate/translate.py](https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/models/rnn/translate/translate.py)

However, they tend to entirely stick to tf.flags in their examples. I have not seen a combination of argpars and tf.flags, yet.

**Comment by MartinThoma** [comment]
Although the `tv train <model.json>` is shorter, it has the advantage of being quite clear to understand.

Anyway, if we can do so depends on how much we can interact with `argparse` before TensorFlow parses the flags. For argparse, it is quite simple to add a [positional argument](https://docs.python.org/2/library/argparse.html#name-or-flags). (But I'm not sure we should do it, even if it is simple)

**Comment by MarvinTeichmann** [comment]
So, you prefer `tv train --config=<model.json>` ?

**Comment by MartinThoma** [comment]
> > Can you give me 3 examples where it is used? Probably there is a common way to combine argparse and tf flags?
> 
> I was referring to the wide usage of tf.flags inside tensorflow

Ok. I thought so. The point is, it is not relevant to us what is standard within Tensorflow code. It is relevant what is standard in the community / the available models.

> So, you prefer `tv train --config=<model.json>` ?

No, I prefer `tv train --config model.json` (but I think argparse automatically allows the one with `=` and without `=`)

**Comment by MarvinTeichmann** [comment]
I was not discussing `tv train --config model.json` vs `tv train --config=model.json`, but `tv train --config model.json` vs `tv train model.json`. The `=` is optional, both options are automatically supported, if the flag config is defined.

**Comment by MartinThoma** [comment]
Yes, I think I prefer being explicit about command line arguments. However, I don't have strong feelings for it. So I'm fine with both.

**Comment by MarvinTeichmann** [comment]
Well after using it a bit I think I would prefer tv-train [--options] <model.json>. Intuitively the model.json is the primary input of tv-train. This feature is however not urgent now. And the question has derived from the original topic.
