### ISSUE TITLE
Change of Naming Convention.

### ISSUE THREAD

**Issue by MarvinTeichmann** [TensorVision/TensorVision#7]
7cac91877555a913b1677ce7de1e6e6dcbc15da6 introduces some new naming convention.

1) --config gets replaced by --hypes to be more consistent with naming inside code.
2) Rundir's are now automatically named (see commit message).

Should we merge the changes to master? Should the default be `--debug` or `--nodebug`?

**Comment by MarvinTeichmann** [comment]
Maybe `--debug` is not the best name. User will expect much more to happen than just a change of naming.

**Comment by MarvinTeichmann** [comment]
Will be discussed in pull request #8.

**Comment by MartinThoma** [comment]
I would rather change it to `config` instead of `hypes`. `config_file = tf.app.flags.FLAGS.config` makes more sense to me than `config_file = tf.app.flags.FLAGS.hypes`

**Comment by MarvinTeichmann** [comment]
Well this line can be changed easily `config_file = tf.app.flags.FLAGS.hypes`. In the rest of the code we refer to the parameters load from that file `hypes`. To you prefer `config['solver']['batch_size']` over `hypes['solver']['batch_size']`?
